const artigosPenais = [
  {
    article: "Art. 31",
    name: "Assédio moral e físico (necessita provas)",
    time: 10,
    trafficTicket: 10000,
    bail: 30000,
    note: "",
    color: "#fff2cc",
  },
  {
    article: "Art. 32",
    name: "Trajes de poderes públicos",
    time: 20,
    trafficTicket: 20000,
    bail: 60000,
    note: "",
    color: "#fff2cc",
  },
  {
    article: "Art. 33",
    name: "Máscara (fora de ação)",
    time: 0,
    trafficTicket: 7000,
    bail: 0,
    note: "",
    color: "#fff2cc",
  },
  {
    article: "Art. 34",
    name: "Uso não autorizado de equipamento da polícia",
    time: 0,
    trafficTicket: 15000,
    bail: 0,
    note: "",
    color: "#fff2cc",
  },
  {
    article: "Art. 35",
    name: "Apologia ao crime (elogia)",
    time: 15,
    trafficTicket: 15000,
    bail: 45000,
    note: "Autor",
    color: "#fff2cc",
  },
  {
    article: "Art. 36",
    name: "Falso testemunho",
    time: 15,
    trafficTicket: 15000,
    bail: 45000,
    note: "",
    color: "#fff2cc",
  },

  {
    article: "Art. 37",
    name: "Resistência a prisão",
    time: 15,
    trafficTicket: 15000,
    bail: 45000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 38",
    name: "Omissão de socorro (necessita de provas)",
    time: 5,
    trafficTicket: 5000,
    bail: 15000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 39",
    name: "Dano a patrimônio (por unidade)",
    time: 5,
    trafficTicket: 5000,
    bail: 15000,
    note: "Por unidade",
    color: "#FFD966",
  },
  {
    article: "Art. 40",
    name: "Difamação (ofensa a honra da pessoa)",
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: "Publicamente",
    color: "#FFD966",
  },
  {
    article: "Art. 41",
    name: "Furto",
    time: 10,
    trafficTicket: 10000,
    bail: 30000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 42",
    name: "Obstrução de justiça",
    time: 30,
    trafficTicket: 30000,
    bail: 90000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 43",
    name: "Agressão corporal culposa (sem intenção)",
    time: 20,
    trafficTicket: 20000,
    bail: 60000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 44",
    name: "Agressão corporal dolosa (com intenção)",
    time: 40,
    trafficTicket: 40000,
    bail: 120000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 45",
    name: "injúria (xingamento/ofensa direta)",
    time: 30,
    trafficTicket: 30000,
    bail: 90000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 46",
    name: "Ameaça (necessita de provas)",
    time: 35,
    trafficTicket: 35000,
    bail: 105000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 47",
    name: "Incitação ao crime (incentivar alguém)",
    time: 20,
    trafficTicket: 20000,
    bail: 60000,
    note: "A terceiro",
    color: "#FFD966",
  },
  {
    article: "Art. 48",
    name: "Fuga (desobediência a ordem de parada)",
    time: 10,
    trafficTicket: 10000,
    bail: 30000,
    note: "",
    color: "#FFD966",
  },
  {
    article: "Art. 49",
    name: "Roubo a caixa bancário ou registradora",
    time: 20,
    trafficTicket: 20000,
    bail: 60000,
    note: "",
    color: "#FFD966",
  },

  {
    article: "Art. 50",
    name: "Desacato (Sem Fiança)",
    time: 15,
    trafficTicket: 15000,
    bail: 0,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 51",
    name: "Extorção (necessita de provas)",
    time: 15,
    trafficTicket: 15000,
    bail: 45000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 52",
    name: "Falsidade ideológica (omitir a verdade, necessita de provas)",
    time: 10,
    trafficTicket: 10000,
    bail: 30000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 53",
    name: "Calúnia (acusação false de crime, necessita de provas)",
    time: 10,
    trafficTicket: 10000,
    bail: 30000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 54",
    name: "Suborno (necessita de provas)",
    time: 10,
    trafficTicket: 10000,
    bail: 30000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 55",
    name: "Atendado ao pudor (assediar alguém)",
    time: 30,
    trafficTicket: 30000,
    bail: 90000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 56",
    name: "Poluição sonora",
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: "SF",
    color: "#F1C232",
  },
  {
    article: "Art. 57",
    name: "Roubo/furto de carro oficial da cidade",
    time: 30,
    trafficTicket: 30000,
    bail: 90000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 58",
    name: "Roubo/furto de veículos",
    time: 20,
    trafficTicket: 20000,
    bail: 60000,
    note: "",
    color: "#F1C232",
  },
  {
    article: "Art. 59",
    name: "Abuso de autoridade",
    time: 30,
    trafficTicket: 30000,
    bail: 90000,
    note: "",
    color: "#F1C232",
  },

  {
    article: "Art. 60",
    name: "Homicídio doloso (com intenção)",
    time: 85,
    trafficTicket: 85000,
    bail: 0,
    note: "SF",
    color: "#BF9000",
  },
  {
    article: "Art. 61",
    name: "Homicídio culposo (sem intenção)",
    time: 50,
    trafficTicket: 50000,
    bail: 0,
    note: "SF",
    color: "#BF9000",
  },
  {
    article: "Art. 62",
    name: "Tentativa de homicídio",
    time: 45,
    trafficTicket: 45000,
    bail: 0,
    note: "SF",
    color: "#BF9000",
  },
  {
    article: "Art. 63",
    name: "Latrocínio (roubou e matou)",
    time: 110,
    trafficTicket: 110000,
    bail: 0,
    note: "SF",
    color: "#BF9000",
  },
  {
    article: "Art. 64",
    name: "Sequestro",
    time: 25,
    trafficTicket: 25000,
    bail: 0,
    note: "SF",
    color: "#BF9000",
  },
  {
    article: "Art. 65",
    name: "Desobediência",
    time: 15,
    trafficTicket: 15000,
    bail: 45000,
    note: "",
    color: "#F1C232",
  },

  {
    article: "Art. 71.1",
    name: "Porte pistola sem registro",
    time: 80,
    trafficTicket: 80000,
    bail: 240000,
    note: "",
    color: "#E06666",
  },
  {
    article: "Art. 71.2",
    name: "Porte de submetralhadora sem registro",
    time: 120,
    trafficTicket: 120000,
    bail: 360000,
    note: "",
    color: "#E06666",
  },
  {
    article: "Art. 71.3",
    name: "Porte de fuzil sem registro",
    time: 150,
    trafficTicket: 150000,
    bail: 450000,
    note: "",
    color: "#E06666",
  },
  {
    article: "Art. 72",
    name: "Mal uso de arma de fogo com registro (cassação do porte)",
    time: 30,
    trafficTicket: 30000,
    bail: 90000,
    note: "",
    color: "#E06666",
  },
];

export default artigosPenais;
