const artigosTransito = [
  {
    article: 'Art. 45 I',
    name: 'Dirigir sem atenção ou sem cuidado a segurança',
    time: 0,
    trafficTicket: 3000,
    bail: 0,
    note: '',
    color: '#f2dcfb',
  },
  {
    article: 'Art. 45 II',
    name: 'Estacionar em acostamentos',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#f2dcfb',
  },
  {
    article: 'Art. 45 III',
    name: 'Luz alta em vias com iluminação',
    time: 0,
    trafficTicket: 3000,
    bail: 0,
    note: '',
    color: '#f2dcfb',
  },
  {
    article: 'Art. 45 IV',
    name: 'Usar buzina prolongada e sucessivamente',
    time: 0,
    trafficTicket: 3000,
    bail: 0,
    note: '',
    color: '#f2dcfb',
  },

  {
    article: 'Art. 46 I',
    name: 'Atirar do veiculo objetos ou substâncias',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 II',
    name: 'Ficar sem combustível na via publica',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 III',
    name: 'Transitar ao lado de outro veículo',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 IV',
    name: 'Transitar em velocidade inferior a metade da máxima',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 V',
    name: 'Usar alarme ou aparelho que produz som perturbante',
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 VI',
    name: 'Estacionar o veiculo em local proibido',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 VII',
    name: 'Exceder o limite de velocidade em até 30% da velocidade permitida',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },
  {
    article: 'Art. 46 VIII',
    name: 'Ultrapassar o sinal vermelho',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#e6b8b7',
  },

  {
    article: 'Art. 47 I',
    name: 'Deixar de usar o cinto de segurança',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 II',
    name: 'Deixar de prestar socorro a vítima de acidente',
    time: 0,
    trafficTicket: 7000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 III',
    name: 'Fazer ou deixar que se faça reparo no veículo em vias rápidas',
    time: 0,
    trafficTicket: 6000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 IV',
    name: 'Transitar na contramão em via de duplo sentido',
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 V',
    name: 'Transitar em marcha ré, salvo para manobras',
    time: 0,
    trafficTicket: 8000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 VI',
    name: 'Desobedecer ordens emanadas da autoridade competente',
    time: 0,
    trafficTicket: 8000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 VII',
    name: 'Deixar de reduzir a velocidade onde o trânsito esteja controlado',
    time: 0,
    trafficTicket: 6000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 VIII',
    name: 'Conduzir o veiculo em má estado de conservação',
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 IX',
    name: 'Evadir-se para não pagar pedágio, quando houver',
    time: 0,
    trafficTicket: 6000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 X',
    name: 'Deixar o motociclista de usar o capacete',
    time: 0,
    trafficTicket: 5000,
    bail: 0,
    note: '',
    color: '#da9694',
  },
  {
    article: 'Art. 47 XI',
    name: 'Exceder o limite de velocidade em até 70% da velocidade permitida',
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#da9694',
  },

  {
    article: 'Art. 48 II',
    name: 'Transitar pela contramão em via de sentido único',
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#963634',
  },
  {
    article: 'Art. 48 III',
    name: 'Deixar de dar passagem a veículos de socorro',
    time: 0,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#963634',
  },
  {
    article: 'Art. 48 IV',
    name: 'Exceder o limite de velocidade acima de 70% da velocidade permitida',
    time: 0,
    trafficTicket: 15000,
    bail: 0,
    note: '',
    color: '#963634',
  },

  {
    article: 'Art. 86',
    name: 'Praticar homicídio culposo (VDM)',
    time: 30,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 86 1º I',
    name: 'Praticar homicídio culposo na faixa de pedestre (VDM)',
    time: 40,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 86 1º II',
    name: 'Praticar homicídio culposo e não prestar socorro (VDM)',
    time: 50,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 86 1º III',
    name: 'Praticar homicídio culposo no exercício de função ou atividade (VDM)',
    time: 60,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 87',
    name: 'Praticar lesão corporal culposa',
    time: 30,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 87 1º',
    name: 'Aumenta-se a pena em qualquer situação do homicídio culposo',
    time: 50,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 86 2º',
    name: 'Conduzir com capacidade psicomotora alterada (álcool ou drogas)',
    time: 40,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 86 3º',
    name: 'Crime acima e o condutor alegar dependência de drogas ou álcool',
    time: 60,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 88',
    name: 'Deixar de prestar socorro imediato a vítima em caso de acidente',
    time: 40,
    trafficTicket: 0,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 89',
    name: 'Afastar-se o condutor do veículo no acidente para não ser responsabilizado',
    time: 30,
    trafficTicket: 15000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 90',
    name: 'Conduzir sob influencia de álcool ou substâncias análogas e expor outrem a danos',
    time: 40,
    trafficTicket: 20000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 91',
    name: 'Participar de corrida, disputa ou competição não autorizada em via pública',
    time: 30,
    trafficTicket: 30000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 91 1º',
    name: 'Crime acima e resultar lesão corporal de outrem',
    time: 40,
    trafficTicket: 30000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 91 2º',
    name: 'Crime acima e resultar morte de outre',
    time: 50,
    trafficTicket: 30000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 92',
    name: 'Trafegar em velocidade incompatível perto de hospitais, praça, DP, etc...',
    time: 20,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
  {
    article: 'Art. 93',
    name: 'Modificar o local do acidente para induzir ao erro a autoridade policial',
    time: 40,
    trafficTicket: 10000,
    bail: 0,
    note: '',
    color: '#b1a0c7',
  },
];

export default artigosTransito;
